//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::admin_entity::Entity as AdminEntity;
pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::officialnews::Entity as Officialnews;
pub use super::professional_player_entity::Entity as ProfessionalPlayerEntity;
pub use super::report_entity::Entity as ReportEntity;
pub use super::spectator_player_entity::Entity as SpectatorPlayerEntity;
pub use super::streams::Entity as Streams;
pub use super::users::Entity as Users;
