//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub age: i32,
    pub display_name: String,
    pub nationality: String,
    pub password: String,
    #[sea_orm(unique)]
    pub username: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::admin_entity::Entity")]
    AdminEntity,
    #[sea_orm(has_many = "super::articles::Entity")]
    Articles,
    #[sea_orm(has_many = "super::comments::Entity")]
    Comments,
    #[sea_orm(has_one = "super::professional_player_entity::Entity")]
    ProfessionalPlayerEntity,
    #[sea_orm(has_many = "super::report_entity::Entity")]
    ReportEntity,
    #[sea_orm(has_one = "super::spectator_player_entity::Entity")]
    SpectatorPlayerEntity,
    #[sea_orm(has_many = "super::streams::Entity")]
    Streams,
}

impl Related<super::admin_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminEntity.def()
    }
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Articles.def()
    }
}

impl Related<super::comments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comments.def()
    }
}

impl Related<super::professional_player_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProfessionalPlayerEntity.def()
    }
}

impl Related<super::report_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportEntity.def()
    }
}

impl Related<super::spectator_player_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpectatorPlayerEntity.def()
    }
}

impl Related<super::streams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Streams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
