variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - deploy
  - test
  - build-sonar

build:
  stage: build
  script:
    - ./gradlew assemble

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose -f docker-compose.yml up -d --build
    - echo "Waiting for MySQL to be ready..."
    - |
      until docker exec mysql mysqladmin ping -h "localhost" --user="springuser" --password="springpass" --silent; do
        echo "MySQL is unavailable - waiting..."
        sleep 5
      done
    - docker ps  # optional: debug running containers
  rules:
    - if: '$CI_COMMIT_BRANCH == "DevelopmentBranch"'

test:
  stage: test
  script:
    - ./gradlew test

build-sonar:
  stage: build-sonar
  environment:
    name: PC
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  script:
    - echo "TOKEN:" $env:SONAR_TOKEN
    - echo "TOKEN LENGTH:" $env:SONAR_TOKEN.length
    - echo "ALL ENV VARS:"
    - powershell -Command "Get-ChildItem Env:"
    - ./gradlew.bat test
    - ./gradlew.bat jacocoTestReport
    - ./gradlew.bat "-Dsonar.host.url=$env:SONAR_HOST_URL" "-Dsonar.login=$env:SONAR_TOKEN" sonar
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'