variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy
  - build-sonar

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - Write-Host "Stopping old containers..."
    - docker compose -f docker-compose.yml down || Write-Host "No containers to stop."

    - Write-Host "Starting containers..."
    - docker compose -f docker-compose.yml up -d --build

    - Write-Host "Waiting for MySQL to be ready using mysql CLI..."

    - |
      $maxAttempts = 20
      $attempt = 0
      while ($true) {
        docker exec mysql mysql -hlocalhost -uspringuser -pspringpass -e "SELECT 1" > $null 2>&1
        if ($LASTEXITCODE -eq 0) {
          Write-Host "✅ MySQL is ready."
          break
        } else {
          Write-Host "❌ MySQL is unavailable (attempt $attempt) - waiting..."
          Start-Sleep -Seconds 5
          $attempt++
          if ($attempt -ge $maxAttempts) {
            Write-Host "❌ Timed out waiting for MySQL."
            exit 1
          }
        }
      }

    - Write-Host "✅ MySQL is up. Listing containers..."
    - docker ps
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "DevelopmentBranch"'


build-sonar:
  stage: build-sonar
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  script:
    - 'echo SONAR_HOST_URL=%SONAR_HOST_URL%'
    - 'echo TOKEN_LEN=%SONAR_TOKEN:~0,0%%SONAR_TOKEN%'
    - cmd /C "gradlew.bat -Dsonar.host.url=%SONAR_HOST_URL% -Dsonar.login=%SONAR_TOKEN% -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300 test jacocoTestReport sonarqube"
  allow_failure: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'