variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy
  - build-sonar

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  image: docker:s3-chessplatform-backend:latest
  script:
    - docker compose -f docker-compose.yml down
    - docker compose -f docker-compose.yml up -d --build
    - echo "Waiting for MySQL to be ready..."
    - >
      bash -c '
        until docker exec mysql mysqladmin ping -h "localhost" --user="springuser" --password="${DATASOURCE_PASS}" --silent; do
          echo "MySQL is unavailable - waiting..."
          sleep 5
        done
      '
    - docker ps
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "DevelopmentBranch"'


build-sonar:
  stage: build-sonar
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
  script:
    - 'echo SONAR_HOST_URL=%SONAR_HOST_URL%'
    - 'echo TOKEN_LEN=%SONAR_TOKEN:~0,0%%SONAR_TOKEN%'
    - cmd /C "gradlew.bat -Dsonar.host.url=%SONAR_HOST_URL% -Dsonar.login=%SONAR_TOKEN% -Dsonar.qualitygate.wait=true -Dsonar.qualitygate.timeout=300 test jacocoTestReport sonarqube"
  allow_failure: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'