spring.application.name=ChessplatformBE

#Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/chessplatform_db
spring.datasource.username=springuser
spring.datasource.password=springpass

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Token
jwt.access-token.secret=E91E158E4C6656F68B1B5D1C316766DE98D2AD6EF3BFB44F78E9CFCDF5
jwt.access-token.exp=15
jwt.access-token.exp-unit=minutes